### ISSUE TITLE
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'TizenInteropCallbacksRegisterSendPort': undefined symbol: TizenInteropCallbacksRegisterSendPort

### ISSUE THREAD

**Issue by ProFive** [flutter-tizen/tizen_interop#29]
I am using the 
  tizen_interop: ^0.2.6
  tizen_interop_callbacks: ^0.1.0
  
E/flutter ( 4668): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'TizenInteropCallbacksRegisterSendPort': undefined symbol: TizenInteropCallbacksRegisterSendPort
E/flutter ( 4668): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
E/flutter ( 4668): #1      new TizenInteropCallbacks._internal (package:tizen_interop_callbacks/tizen_interop_callbacks.dart:105:10)
E/flutter ( 4668): #2      new TizenInteropCallbacks (package:tizen_interop_callbacks/tizen_interop_callbacks.dart:96:41)
  
  
    static void appconnBwResultCallback(int deviceId, Pointer<Int8> sid, Pointer<AppconnBwResult> result) {
  }

  static void appconnIperfTest({required TizenInteropCallbacks callbacks, required int deviceId, required String sid, required int targetPort, required int testDurationSec, required int maxBwTest, required int blocking}) {
    Pointer<Int8> _sid = sid.toNativeUtf8().cast<Int8>();
    final callback = callbacks.register<AppconnBwResultCallback>('appconnBwResultCallback', Pointer.fromFunction<AppconnBwResultCallback>(appconnBwResultCallback));
    _appconnIperfTest(deviceId, _sid, targetPort, testDurationSec, maxBwTest, blocking, callback.interopCallback);
  }

**Comment by swift-kim** [comment]
Did you use `flutter-tizen run` to launch your app?
